---
- name: Create zk group
  group:
    name: "{{ item }}"
    state: present
  loop:
    - zookeeper

- name: Create zk user
  user:
    name: "{{ item }}"
    home: "/home/{{ item }}"
    group: "{{ item }}"
    shell: /sbin/nologin
    state: present
  loop:
    - zookeeper

- name: Create zk dir
  file:
    path: "{{ item }}"
    state: directory
    owner: zookeeper
    group: zookeeper
  with_items:
    - "/home/zookeeper/_package"
    - "/home/zookeeper/dataDir"

- name: set node id
  shell: echo "{{ ansible_zk_id }}" > /home/zookeeper/dataDir/myid && chown zookeeper.zookeeper /home/zookeeper/dataDir/myid

- name: extract zk binary
  unarchive:
    src: "/tmp/zookeeper-{{ version['zk'] }}.tar.gz"
    dest: /home/zookeeper/_package/
    owner: zookeeper
    group: zookeeper

- name: copy config template
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: zookeeper
    group: zookeeper
  with_items:
    - { src: zoo_sample.cfg.j2, dest: "/home/zookeeper/_package/conf/zoo.cfg", mode: 755 }

- name: update config
  blockinfile:
    path: "/home/zookeeper/_package/conf/zoo.cfg"
    marker: "# ansible managed zk node"
    block: "server.{{ hostvars[item]['ansible_zk_id'] }}={{ hostvars[item]['ansible_ssh_node'] }}:3181:4181"
    state: present
    owner: zookeeper
    group: zookeeper
  with_inventory_hostnames: ["zookeeper"]

- name: copy zk unit file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: zookeeper
    group: zookeeper
  with_items:
    - { src: zookeeper.service.j2, dest: "/etc/systemd/system/zookeeper.service", mode: 755 }
  notify:
    - enable and start zookeeper
  tags:
    - config

- name: copy exporter binary
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: root
    group: root
  with_items:
    - { src: zookeeper-exporter, dest: /root/exporters/, mode: 755 }

- name: deploy zk exporter
  blockinfile:
    path: /root/exporters/start_exporter.sh
    marker: "# managed by ansible"
    block: "cd /root/exporters && nohup ./zookeeper-exporter --zk-hosts={{ ansible_ssh_host }}:2181 &"
    state: present
  notify:
    - start zk exporter
