---
- hosts: ops
  tasks:
    - name: download packages
      uri:
        url: https://download2274.mediafire.com/2h3gwa8vl1lg/rbjvv6is71cnvok/jdk-{{ version['java'] }}-linux-x64.rpm
        dest: /tmp/
      with_items:
        - https://download2274.mediafire.com/rmxkv6e2hsig/rbjvv6is71cnvok/jdk-{{ version['java'] }}-linux-x64.rpm
        - https://dlcdn.apache.org/zookeeper/zookeeper-{{ version['zk'] }}/apache-zookeeper-{{ version.zk] }}-bin.tar.gz
        - https://dlcdn.apache.org/kafka/{{ version['kafka'] }}/kafka_{{ version['scala'] }}-{{ version['kafka'] }}.tgz

- name: init system
  hosts: all
  roles:
    - role: node

- name: deploy zk
  hosts: zookeeper
  roles:
    - role: zookeeper

- name: deploy kafka
  hosts: kafka
  roles:
    - role: kafka
