---
- hosts: ops
  vars_files:
    - versions.yml
  tasks:
    - name: download packages
      uri:
        url: "{{ item }}"
        dest: /tmp/
      with_items:
        - "https://shared-objects.oss-cn-qingdao.aliyuncs.com/jdk-{{ version['java'] }}-linux-x64.rpm"
        - "https://shared-objects.oss-cn-qingdao.aliyuncs.com/zookeeper-{{ version['zk'] }}.tar.gz"
        - "https://shared-objects.oss-cn-qingdao.aliyuncs.com/kafka_{{ version['scala'] }}-{{ version['kafka'] }}.tar.gz"

- name: init system
  hosts: all
  roles:
    - role: node

- name: deploy zk
  hosts: zookeeper
  roles:
    - role: zookeeper

- name: deploy kafka
  hosts: kafka
  roles:
    - role: kafka
