---
- name: download binary packages
  hosts: ops
  roles:
    - role: ops

- name: init system
  hosts: node
  roles:
    - role: node

- name: deploy zk
  hosts: zookeeper
  roles:
    - role: zookeeper

- name: deploy kafka
  hosts: kafka
  roles:
    - role: kafka
