---
- hosts: ops
  vars_files:
    - versions.yml
  tasks:
    - name: download packages
      uri:
        url: "{{ item }}"
        dest: /tmp/
      with_items:
        - "https://anonfiles.com/n413z2O8xe/jdk-{{ version['java'] }}-linux-x64_rpm"
        - "https://dlcdn.apache.org/zookeeper/zookeeper-{{ version['zk'] }}/apache-zookeeper-{{ version['zk'] }}-bin.tar.gz"
        - "https://dlcdn.apache.org/kafka/{{ version['kafka'] }}/kafka_{{ version['scala'] }}-{{ version['kafka'] }}.tgz"

- name: init system
  hosts: all
  roles:
    - role: node

- name: deploy zk
  hosts: zookeeper
  roles:
    - role: zookeeper

- name: deploy kafka
  hosts: kafka
  roles:
    - role: kafka
