---
- name: enable and start kafka
  service:
    name: kafka
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: start kafka exporter
  shell: "cd /root/exporters && nohup ./kafka_exporter --kafka.server={{ ansible_ssh_node }}:9092 &"