---
- name: enable and start zookeeper
  service:
    name: zookeeper
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: start zk exporter
  shell: "cd /root/exporters && nohup ./zookeeper-exporter --zk-hosts={{ ansible_ssh_host }}:2181 &"
