---
- name: transfer binary file
  copy:
    src: "/tmp/jdk-{{ version['java'] }}-linux-x64.rpm"
    dest: /tmp/

- name: install rpm package
  shell: "yum localinstall -y /tmp/jdk-{{ version['java'] }}-linux-x64.rpm"

- name: set java environment
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: root
    group: root
  with_items:
    - { src: profile.j2, dest: /etc/profile, mode: 755 }
  notify:
    - update java environment

- name: set hosts
  blockinfile:
    path: /etc/hosts
    marker: '# managed by ansible'
    block: "{{ hostvars[item]['ansible_ssh_host'] }}\t{{ hostvars[item]['ansible_ssh_node'] }}"
    state: present
  with_inventory_hostnames: ["node"]

- name: copy exporter scripts
  template:
    src: start_exporter.sh.j2
    dest: /root/exporters/start_exporter.sh
    mode: 755

- name: set auto start
  cron:
    name: start exporters
    job: /root/exporters/start_exporter.sh
    special_time: reboot
  notify: start exporter
